[package]
name = "rpc-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
rpc-codec = { path = "../rpc-codec" }
quinn = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
rustls = { workspace = true }
